stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-adoptopenjdk-11
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-pubsub:vega-modpubsub-78
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-jqjbc:folijet-helmcharts-mod-pubsub
      version: 0.1.31
      answers:
        image.repository: docker.dev.folio.org/mod-pubsub
        image.tag: vega-modpubsub-78
      targetNamespace: vega
      name: mod-pubsub
timeout: 60
notification: {}
